//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT_Assignment_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS4
    {
        public int Id { get; set; }
        public string game_name { get; set; }
        public string genre { get; set; }
        public string year { get; set; }
    }
}
