USE [Games]
GO
/****** Object:  Table [dbo].[PC]    Script Date: 22-Dec-20 11:49:14 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PC](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[game_name] [varchar](50) NULL,
	[genre] [varchar](50) NULL,
	[year] [varchar](50) NULL,
 CONSTRAINT [PK_PC] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PS4]    Script Date: 22-Dec-20 11:49:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PS4](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[game_name] [varchar](50) NULL,
	[genre] [varchar](50) NULL,
	[year] [varchar](50) NULL,
 CONSTRAINT [PK_PS4] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Xbox]    Script Date: 22-Dec-20 11:49:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Xbox](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[game_name] [varchar](50) NULL,
	[genre] [varchar](50) NULL,
	[year] [varchar](50) NULL,
 CONSTRAINT [PK_Xbox] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
